version: '2'
services:
  spark-master:
    build: ./img      
    container_name: spark-master
    hostname: spark-master
    command: ./start-master.sh
    ports:
      - 8080:8080       
      - 7077:7077  

  spark-slave:
    build: ./img      
    container_name: spark-slave
    hostname: spark-slave
    command: ./start-slave.sh
    depends_on:
      - spark-master     
    ports:
      - 8081:8081       
      - 7078:7078  
        
    
