version: '2'
services:
  spark-master:
    build: ./img      
    container_name: spark-master
    hostname: spark-master
    command: ./start-master.sh
    ports:
      - 8080:8080       
      - 7077:7077  
        
  spark-slave-1:
    build: ./img      
    container_name: spark-slave-1
    hostname: spark-slave-1
    command: ./start-slave.sh
    depends_on:
      - spark-master     
    ports:
      - 8081:8081       
      - 7078:7078  
    environment:    
      - SLAVE_PORT=7078
      - MEMORY=1024m  

  spark-slave-2:
    build: ./img      
    container_name: spark-slave-2
    hostname: spark-slave-2
    command: ./start-slave.sh
    depends_on:
      - spark-master     
    ports:
      - 8082:8081       
      - 7079:7079  
    environment:    
      - SLAVE_PORT=7079
      - MEMORY=1024m
    
  spark-slave-3:
    build: ./img      
    container_name: spark-slave-3
    hostname: spark-slave-3
    command: ./start-slave.sh
    depends_on:
      - spark-master     
    ports:
      - 8083:8081       
      - 7080:7080  
    environment:    
      - SLAVE_PORT=7080
      - MEMORY=128m
